### ISSUE TITLE
in controller

### ISSUE THREAD

**Issue by benn876** [raduandreipopescu/budget-app#2]
nu trebuie sa mai ai un try-catch. Daca vrei sa trimiti o eroare frumoasa/custom catre client folosim  @ControllerAdvice

**Comment by raduandreipopescu** [comment]
Am adaugat RestExceptionHandler in loc de blocul try-catch.
Arata mai bine si mi-am amintit ca ne-ai aratat pe finalul cursului trecut.

Multumesc.
